runtime: python38
env: flex

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.8

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
